### ISSUE TITLE
Last issue removed

### ISSUE THREAD

**Issue by eugenividal** [saturnlighting/road-traffic-fatalities-by-light-condition#1]
Due to capacity issues, I had to remove and create again this repository. As a result, previous issues were removed. @Robinlovelace could you please open again the last issue you created? It was about a journalist comparing road traffic fatalities in the US and in other 'developed' counties. Thanks!

**Comment by Robinlovelace** [comment]
Sure thing and no probs, good thinking to create a new repo, will do!

**Comment by Robinlovelace** [comment]
Here's the link to Paul Krugman, interesting statistics in this thread: https://fosstodon.org/@pkrugman@mastodon.online/109415626667918817

**Comment by eugenividal** [comment]
Thanks, @Robinlovelace. I'll take this into account. Although I cannot access the article. Interesting stats. I was thinking of estimating the risk (deaths by 100 million miles) by light conditions (daylight/dark), which I am almost sure nobody did before. Closing this issue now.

**Comment by Robinlovelace** [comment]
No problem Eugeni, thank you : )
