### ISSUE TITLE
Road traffic fatalities from 2011 to 2015 UK

### ISSUE THREAD

**Issue by eugenividal** [saturnlighting/road-traffic-fatalities-by-light-condition#1]
I am trying to get the last 10 years of road traffic fatalities for both US and the UK. I managed to get the data for the US (see below). However, I couldn't find 2011-2015 data for the UK. Do you know if this data is somewhere available, @Robinlovelace?

![Screenshot from 2022-11-27 10-59-16](https://user-images.githubusercontent.com/32644567/204131726-52fffcdc-b005-43b0-97fa-55748ff6acf1.png)

**Comment by Robinlovelace** [comment]
Hey @eugenividal good question, I imagine the data is in STATS19, right? Would need to filter out `Severity == "Fatal"` I believe.

**Comment by eugenividal** [comment]
Hi @Robinlovelace, thanks for your response. The problem is that before 2016 the data does not exist in the package. 

```
> a15 = get_stats19(2015, "ac")
No files of that type found for that year.
No files found. Check the stats19 website on data.gov.uk
Files identified: 

   
Error in if (is_zip_file) { : argument is of length zero
```

**Comment by Robinlovelace** [comment]
Agreed, there is definitely an issue, many thanks for reporting and the reproducible example (reprex). I can reproduce this bug in the stats19 package and have opened an issue: https://github.com/ropensci/stats19/issues/219

**Comment by Robinlovelace** [comment]
Good news @eugenividal, I think I've found a way to get the data:

```r
# Aim: test 2015 data
remotes::install_github("ropensci/stats19")
library(stats19)
# ?get_stats19
crashes_2017 = get_stats19(2017, type = "accident")
# crashes_2015 = get_stats19(2015, type = "accident") # Fails

# Looking to get raw data:
# https://www.data.gov.uk/dataset/cb7ae6f0-4be6-4935-9277-47e5ce24a11f/road-safety-data
data_dir = stats19:::get_data_directory()
u = "https://data.dft.gov.uk/road-accidents-safety-data/dft-road-casualty-statistics-casualty-1979-2021.csv"
f = basename(u)
f = file.path(data_dir, f)
if(!file.exists(f)) {
  download.file(u, f)
}
casualties_all_raw = readr::read_csv(f)
casualties_all = format_casualties(casualties_all_raw)
```

Does that work for you? Apologies for the bug in the `stats19` package, definitely needs a bit of work.

**Comment by eugenividal** [comment]
That works, Robin. Thanks!!! I close the issue now.
